export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const CHANGE_NAME_FIELD = 'CHANGE_NAME_FIELD';
export const CHANGE_EMAIL_FIELD = 'CHANGE_EMAIL_FIELD';
export const CHANGE_COUNT = 'CHANGE_COUNT';